const containerList = [
    {
        cotainers: [
            {
                operator_note: "Q-production A1",
                container_type_id: 2,
                solution_name: "Production medium",
                solution_initial_volume_mL: null,
                inventory_location: "ferm-4th floor",
                id: 13,
                solution_description: null,
            },
            {
                operator_note: "0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 26,
                solution_description: null,
            },
            {
                operator_note: "16h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 39,
                solution_description: null,
            },
            {
                operator_note: "20h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 51,
                solution_description: null,
            },
            {
                operator_note: "24h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 63,
                solution_description: null,
            },
            {
                operator_note: "28h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 75,
                solution_description: null,
            },
            {
                operator_note: "40h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 87,
                solution_description: null,
            },
            {
                operator_note: "44h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 99,
                solution_description: null,
            },
            {
                operator_note: "48h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 111,
                solution_description: null,
            },
            {
                operator_note: "52h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 123,
                solution_description: null,
            },
            {
                operator_note: "64h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 135,
                solution_description: null,
            },
            {
                operator_note: "68h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,

                inventory_location: "fridge",
                id: 147,
                solution_description: null,
            },
            {
                operator_note: "72h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,

                inventory_location: "fridge",
                id: 159,
                solution_description: null,
            },
            {
                operator_note: "76h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 171,
                solution_description: null,
            },
            {
                operator_note: "88h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 183,
                solution_description: null,
            },
            {
                operator_note: "92h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: 5,
                inventory_location: "fridge",
                id: 195,
                solution_description: null,
            },
            {
                operator_note: "Q solid SD1274-001",
                container_type_id: 3,
                solution_name: null,
                solution_initial_volume_mL: 25,
                inventory_location: "ferm 4th floor",
                id: 219,
                solution_description: null,
            },
            {
                operator_note: "SF1-1 SD1274-001",
                container_type_id: 5,
                solution_name: null,
                solution_initial_volume_mL: 120,
                inventory_location: "4th ",
                id: 225,
                solution_description: null,
            },
            {
                operator_note: "SF3-1",
                container_type_id: 5,
                solution_name: null,
                solution_initial_volume_mL: 120,
                inventory_location: "4th",
                id: 231,
                solution_description: null,
            },
            {
                operator_note: "SFN-1-1",
                container_type_id: 8,
                solution_name: null,
                solution_initial_volume_mL: 1000,
                inventory_location: "4th",
                id: 237,
                solution_description: null,
            },
            {
                operator_note: "Inoculation A1",
                container_type_id: 9,
                solution_name: null,
                solution_initial_volume_mL: 250,
                inventory_location: "4th",
                id: 244,
                solution_description: null,
            },
            {
                operator_note: "100.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1589,
                solution_description: null,
            },
            {
                operator_note: "120.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1601,
                solution_description: null,
            },
            {
                operator_note: "130.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1613,
                solution_description: null,
            },
            {
                operator_note: "140.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1625,
                solution_description: null,
            },
            {
                operator_note: "150.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1637,
                solution_description: null,
            },
            {
                operator_note: "160.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1649,
                solution_description: null,
            },
            {
                operator_note: "100.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1661,
                solution_description: null,
            },
            {
                operator_note: "120.0h-A1",
                container_type_id: 4,
                solution_name: null,
                solution_initial_volume_mL: null,
                inventory_location: "fridge",
                id: 1673,
                solution_description: null,
            },
        ],
    },
    {
        container_transfers: [
            {
                id: 23,
                destination_container_id: 13,
                amount_transferred_unit: "mL",
                source_container_id: 244,
                amount_transferred: 250,
            },
            {
                id: 22,
                destination_container_id: 244,
                amount_transferred_unit: "mL",
                source_container_id: 237,
                amount_transferred: 50,
            },
            {
                id: 24,
                destination_container_id: 244,
                amount_transferred_unit: "mL",
                source_container_id: 237,
                amount_transferred: 200,
            },
            {
                id: 3,
                destination_container_id: 237,
                amount_transferred_unit: "mL",
                source_container_id: 231,
                amount_transferred: 50,
            },
            {
                id: 2,
                destination_container_id: 231,
                amount_transferred_unit: "mL",
                source_container_id: 225,
                amount_transferred: 2,
            },
            {
                id: 1,
                destination_container_id: 225,
                amount_transferred_unit: "colonies",
                source_container_id: 219,
                amount_transferred: 10,
            },
            {
                id: 25,
                destination_container_id: 26,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1111,
                destination_container_id: 39,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 27,
                destination_container_id: 63,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 28,
                destination_container_id: 75,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 29,
                destination_container_id: 87,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 30,
                destination_container_id: 99,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 31,
                destination_container_id: 111,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 32,
                destination_container_id: 51,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 33,
                destination_container_id: 123,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 34,
                destination_container_id: 135,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 35,
                destination_container_id: 147,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 36,
                destination_container_id: 159,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 37,
                destination_container_id: 171,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 38,
                destination_container_id: 183,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 2222,
                destination_container_id: 195,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1372,
                destination_container_id: 1589,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1384,
                destination_container_id: 1601,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1396,
                destination_container_id: 1613,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1408,
                destination_container_id: 1625,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1420,
                destination_container_id: 1637,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1432,
                destination_container_id: 1649,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1444,
                destination_container_id: 1661,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
            {
                id: 1456,
                destination_container_id: 1673,
                amount_transferred_unit: "mL",
                source_container_id: 13,
                amount_transferred: 5,
            },
        ],
    },
]

export { containerList }